[package]
name = "ray"
version = "0.1.0"
authors = ["Stephen Becker IV <github@deathbyescalator.com>"]
[dependencies]
image = "0.6.1"
nalgebra = "0.5.1"
rand = "0.3"
simple_parallel = "0.3"
flame = "0.1.5"
